### ISSUE TITLE
RFE: Implement log caching to reduce possible failure of Restraint 

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/restraint#94]
Some days ago I observed weird behavior in Restraint execution. This happens during peak of running jobs across all locations.
```
[root ~]# systemctl status restraintd
● restraintd.service - The restraint harness.
Loaded: loaded (/usr/lib/systemd/system/restraintd.service; enabled; vendor preset: disabled)
Active: active (running) since Fri 2020-01-17 10:40:55 EST; 24min ago
Process: 1748 ExecStartPre=/usr/bin/check_beaker (code=exited, status=0/SUCCESS)
Main PID: 1757 (restraintd)
CGroup: /system.slice/restraintd.service
├─ 1757 /usr/bin/restraintd
├─ 1865 make run
├─ 1878 /bin/bash ./runtest.sh
├─11359 /usr/bin/rstrnt-report-result --rhts Test PASS /tmp/tmp.7nwdD9Q9TF 0
├─11420 /bin/bash -l /usr/share/restraint/plugins/task_run.d/10_bash_login /usr/share/restraint/plugins/task_run.d/15_beakerlib /usr/share/restraint/plugins/task_run.d/20_unconf...
├─11442 /bin/sh /usr/share/restraint/plugins/run_plugins
├─11463 /bin/sh ./10_localwatchdog
└─11465 rstrnt-report-result --no-plugins /10_localwatchdog WARN 0

Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: gpg: Signature made Fri 17 Jan 2020 10:51:25 AM EST using DSA key ID AA7488BA
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: gpg: Good signature from "bob-dsa-4096 <bob-dsa-4096@foo.bar>"
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: [ 10:51:26 ] :: [ PASS ] :: Veryfing all Bob's dsa 4096 bit key signs (except detac..., got 0)
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: [ 10:51:26 ] :: [ BEGIN ] :: Removing signatures :: actually running 'rm text.msg-si...-signed'
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: [ 10:51:26 ] :: [ PASS ] :: Removing signatures (Expected 0, got 0)
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: Duration: 544s
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: Assertions: 2157 good, 0 bad
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: :: RESULT: PASS (Test)
Jan 17 10:56:33 the-best-p8-kvm-from-ibm.hatred.com restraintd[1757]: ** Test PASS Score:0
Hint: Some lines were ellipsized, use -l to show in full.

[root ~]# ps aux | grep rstrnt
root 11359 0.0 0.0 157760 5888 ? Sl 10:51 0:00 /usr/bin/rstrnt-report-result --rhts Test PASS /tmp/tmp.7nwdD9Q9TF 0
root 11465 0.0 0.0 157760 5760 ? Sl 10:56 0:00 rstrnt-report-result --no-plugins /10_localwatchdog WARN 0
root 11709 0.0 0.0 111552 3200 pts/1 S+ 11:06 0:00 grep --color=auto rstrnt

[root ~]# date
Fri Jan 17 11:06:53 EST 2020
```

As you can see. tests is finished however report-result wasn't moving.

After further investigation, I noticed that the request to BKR LC took around 30 sec. And Restraint had ~110 items in message queue. So you can imagine how long it will take to empty the queue.

My proposal here is to start aggregating results before blindly appending them into queue which needs to be processed one by one. We don't need to have harness.log output line by line.

**Comment by danrodrig** [comment]
@ernestask implemented a log manager for this and it was going in the right direction. I rebased it on top of master in https://github.com/danrodrig/restraint/tree/log-manager

@ernestask if you are fine with it, I would like to continue that work.

**Comment by ernestask** [comment]
![portrait-happy-senior-man-thumb-up-16276754.jpg](https://user-images.githubusercontent.com/26867637/87051011-51b72600-c1ff-11ea-9efc-5e90cf20ef45.jpg)

**Comment by danrodrig** [comment]
@ernestask thanks.

**Comment by cbouchar** [comment]
Daniel: 
You may have addressed these issues already but these comments below are from my last email sent to Ernestas.
The job results have since disappeared but the job can still be cloned and rerun.
Carol
Comments from last email:
-----------------------------------
The timing of your call to rstrnt_upload_logs in task.c state TASK_COMPLETED
is not correct because it is 'important' to see the following at the end of harness.log for most tasks.
** Completed Task : 183582
I tried a fix for this without success. I have my hands in a number
of other issues so stopped taking it further.  Here are the runs where
you can observe incorrect behavior:

latest (before)
https://beaker-devel.app.eng.bos.redhat.com/jobs/18308
ern-log2 (after)
https://beaker-devel.app.eng.bos.redhat.com/jobs/18358

There is one exception to this rule and that is when we perform aborts
and that looks good until I see taskout.log and harness.log in the task
which follows when there should be none.  Here are the runs where you
can observe incorrect behavior:

latest (before)
https://beaker-devel.app.eng.bos.redhat.com/jobs/18309
ern-log2 (after)
https://beaker-devel.app.eng.bos.redhat.com/jobs/18353
